# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'Pilot Ace' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '14.0'
  # Pods for Pilot Ace

  target 'Pilot AceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Pilot Ace TV' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :tvos, '14.0'
  # Pods for Pilot Ace TV

end
